# Writes build_info_gen.h with version, git commit, repository and build
# channel. Runs on every build (see CMakeLists.txt) but only rewrites the
# header when something changed, so it costs no recompilation otherwise.
#
# Inputs (-D): SRC_DIR, OUT_FILE, VERSION.
# Environment overrides for builds without .git (tarballs, CI):
#   FACET_BUILD_COMMIT, FACET_BUILD_REPO, FACET_BUILD_CHANNEL (dev|release).

set(commit "")
set(dirty 0)
set(repo "")
set(tag "")

find_package(Git QUIET)
if(GIT_FOUND)
    execute_process(COMMAND ${GIT_EXECUTABLE} -C ${SRC_DIR} rev-parse --short=12 HEAD
                    OUTPUT_VARIABLE commit OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET RESULT_VARIABLE rc)
    if(rc EQUAL 0)
        execute_process(COMMAND ${GIT_EXECUTABLE} -C ${SRC_DIR} status --porcelain
                        OUTPUT_VARIABLE status OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
        if(NOT status STREQUAL "")
            set(dirty 1)
        endif()
        execute_process(COMMAND ${GIT_EXECUTABLE} -C ${SRC_DIR} config --get remote.origin.url
                        OUTPUT_VARIABLE repo OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
        execute_process(COMMAND ${GIT_EXECUTABLE} -C ${SRC_DIR} describe --exact-match --tags HEAD
                        OUTPUT_VARIABLE tag OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    else()
        set(commit "")
    endif()
endif()

if(DEFINED ENV{FACET_BUILD_COMMIT})
    set(commit "$ENV{FACET_BUILD_COMMIT}")
endif()
if(DEFINED ENV{FACET_BUILD_REPO})
    set(repo "$ENV{FACET_BUILD_REPO}")
endif()

# Never leak credentials; show "host/owner/name".
string(REGEX REPLACE "^[a-z+]+://([^@/]*@)?" "" repo "${repo}")
string(REGEX REPLACE "^git@([^:]+):" "\\1/" repo "${repo}")
string(REGEX REPLACE "\\.git$" "" repo "${repo}")

if(DEFINED ENV{FACET_BUILD_CHANNEL})
    set(channel "$ENV{FACET_BUILD_CHANNEL}")
elseif(tag STREQUAL "v${VERSION}" AND dirty EQUAL 0)
    set(channel "release")
else()
    set(channel "dev")
endif()

string(TIMESTAMP date "%Y-%m-%d" UTC)

set(content "// Generated by cmake/build_info.cmake. Do not edit.
#pragma once
#define FACET_BUILD_VERSION \"${VERSION}\"
#define FACET_BUILD_CHANNEL \"${channel}\"
#define FACET_BUILD_COMMIT \"${commit}\"
#define FACET_BUILD_DIRTY ${dirty}
#define FACET_BUILD_REPO \"${repo}\"
#define FACET_BUILD_DATE \"${date}\"
")

set(old "")
if(EXISTS "${OUT_FILE}")
    file(READ "${OUT_FILE}" old)
endif()
if(NOT old STREQUAL content)
    file(WRITE "${OUT_FILE}" "${content}")
endif()
